language: python
python:
  - "3.6"

sudo: required

services:
  - docker

env:
  - TOX_ENV=py36
  - TOX_ENV=flake8

matrix:
  fast_finish: true

install:
  - pip install tox

script: tox -e $TOX_ENV

after_success:
  - docker --version  # document the version travis is using
